language: python
python: 3.7

install:
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda

- conda env create -q environment.yml
- conda activate tensorplane-dev

- conda install pytest-cov
- conda install -c conda-forge codecov

- python setup.py install

script:
- py.test --cov-report=xml --cov=tensorplane tensorplane/tests/

after_success:
- codecov

deploy:
  password:
    secure: jjtcea+M/THmrcNuYh7GryrDqE3k44G9GgXovaabBAP5ZoVVHCix/+FoZW0diPIiNYNNPAox/cmXIAiU/hbkSiM4sEXdM9jkQ1EBa/75nevolUumGozRdQ0i+ioWH/CFLIvaCiHbA7hmR6Ac1EnRR/sZFJryECqy7kuh4FgSlg1DT4kg3wPbWEQaoCH+K5L275nIWoQ9e63pIahQTB8MGRiWeiz5BYcXnwMZliKu66wCBd9WVTIPwAnxmdqPr4ttFGg/LGkpQTkYhqdKp36uBKoSqFo7eQKcp3gJe6gFPjqn0sx2HbXlUR/BmmPTRJh22xLQ+oGFXhK32QO9ehv2AWspoHiK/Vxym4S5yCxvn2rAoUdYxBwy2RToKKijawB4QUagDbu9zoFrfOtxaDpihixQJTalw5780YrvngzELLHsbS9CNBiTpBfKxvzt1HVLysczplJBKN4bqu445wzj7BjN2VHvU6chTBUSI7CpxxA7rPGIz1I84PY9NREFalYmJrMJfd2QGP9WOyMT+NG7BuKZciX8jK1O5RsgNYdnAU/0WZUEC5mbGAMh4CwEiap/Pt7Vs/bkHshF6f0ZX87AV7lQQMyvRcaOjOuc9YRzUVnjXv4vc2bk4NMFmYKlr/clZlF7nmqqsd0PXS7Ondfi9BDTHyYwcxFerY8Ujj2PWts=
  on:
    tags: true
