language: python
python: 3.7

# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
install:
  - sudo apt-get update

  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  - conda info -a

  - conda env create -q environment.yml
  - conda activate tensorplane-dev

  - conda install -c conda-forge codecov
  
  - python setup.py install

script:
  - py.test --cov-report=xml --cov=tensorplane tensorplane/tests/

after_success:
  - codecov
